# Site settings
title: David Enders
email: david.georg.enders@gmail.com
description: Software engineer in Claremont, CA
keywords: "Software Engineer, Python, C++, AWS, Full-stack, Machine Learning, AI, Claremont, Claremont McKenna College, Harvey Mudd College"
baseurl: ""
url: ""

# Social networks usernames
social:
  - github: https://github.com/davidenders11
  - linkedin: https://www.linkedin.com/in/david-enders/
  - medium: https://medium.com/@denders24

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links

# Build settings
markdown: kramdown
permalink: pretty

relative_links:
  enabled: true
  collections: true

include:
  - posts.html
