project:
  type: website
  output-dir: docs

website:
  title: "David Enders"
  search: false
  repo-url: https://github.com/quarto-dev/quarto-demo
  navbar:
    left:
      - icon: github
        href: https://github.com/davidenders11
      - icon: linkedin
        href: https://linkedin.com/in/david-enders
      - icon: medium
        href: https://medium.com/@davidenders
    right:
      - href: /resume.pdf
        text: Resume
      - posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
